# Generated by Django 5.2.12 on 2026-04-23 16:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='organizingCommittees',
            field=models.ManyToManyField(related_name='organized_conferences', through='conferenceApp.OrganizingCommittee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='userSubmissions',
            field=models.ManyToManyField(related_name='submitted_conferences', through='conferenceApp.Submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'Description must be at least 30 characters long'), django.core.validators.MaxLengthValidator(300, 'Description must have at most 300 characters')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
