# Generated by Django 5.2.12 on 2026-04-25 14:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0002_conference_organizingcommittees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='keywords',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and can include spaces', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
