# Generated by Django 5.2.12 on 2026-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
