# Generated by Django 5.2.12 on 2026-04-25 14:25

import django.core.validators
import userApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[userApp.models.validateEmail]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Name must have more characters'), django.core.validators.RegexValidator(message='Name must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'Name must have more characters'), django.core.validators.RegexValidator(message='Name must contain only letters', regex='^[a-zA-Z]+$')]),
        ),
    ]
